### ISSUE TITLE
Text fields not selectable for entry on mobile

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/composer#1]
On all iOS clients tested (Firefox, Safari, Chrome) text fields are not selectable for text entry. These highlight when tapped, but text entry is not activated / possible (no keyboard control activates, or focus provided if using external keyboard).

**Comment by MrYuion** [comment]
All browsers in iOS run through Safari. This issue doesn't show up on the iOS simulator. I don't have an iOS device which makes it a bit hard for me to test.
https://drive.google.com/file/d/12BWHR8_gpcTuyHuEHSiOaWl05jQZTjUc/view?usp=sharing

**Comment by kimburgess** [comment]
Just pulled the latest build for the backoffice build and it’s now working in all fields there. It does still persist on the auth screen though.

https://drive.google.com/file/d/12BWHR8_gpcTuyHuEHSiOaWl05jQZTjUc/view?usp=sharing

Let me know if there’s anything I can test, or info you need in lieu of a local device.

**Comment by MrYuion** [comment]
Not sure why the login form is an issue. The form elements are exactly the same as other forms in the application. It should redirect to the old style login page for auth so there shouldn't be any issues anyways.

**Comment by kimburgess** [comment]
The old style login shows on first load (and works), but if you hit backoffice again with an invalid session it shunts you to the auth UI in the video I linked.

**Comment by MrYuion** [comment]
That's due the backend returning 404 for the current user. I think Steve is working on that.

**Comment by MrYuion** [comment]
Is this working on the latest version?

**Comment by kimburgess** [comment]
Yep.
